services:
  backend:
    build: .
    restart: unless-stopped
    environment:
      - AMBIENTE=desenvolvimento
      - DATABASE_URL=postgresql://admin:admin@db:5432/measures_database
    entrypoint:
      - /usr/app/backend/entrypoint.sh
    command: npm run dev
    volumes:
      - ./:/usr/app/backend
    depends_on:
      - db
    ports:
      - "3333:3333"
      - "5555:5555"




  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: measures_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: